### ISSUE TITLE
Can GRIPT works with multi-sample vcf?

### ISSUE THREAD

**Issue by ionicbond2005** [fe4960/GRIPT_BCM#2]
HI,

I am planning to use GRIPT for my analysis. However, when I look at the examples, it seems that each vcf represents one sample. Can GRIPT work with vcf which have multiple samples? Or do I have to separate that into one vcf/sample?

Thanks

Samuel Li

**Comment by fe4960** [comment]
Hi Samuel,

GRIPT can't work with vcf with multiple samples. The data need to be separated into one vcf per sample.

Best regards,
Jun
