### ISSUE TITLE
issue about pre-processing

### ISSUE THREAD

**Issue by fjmuzengyiheng** [fe4960/GRIPT_BCM#4]
Hi, thank you for providing this first-tier tool.

I have been trying to build GRIPT pipeline in our lab, but I stuck here:

###My pre-processing command###
work_dir=$(pwd)
gript_dir=/genetics/home/zengyiheng/project/zyh-pipeline/gript/GRIPT_BCM
snpeff_jar=/genetics/home/zengyiheng/project/zyh-pipeline/snpeff/snpEff/snpEff.jar
snpeff_config=/genetics/home/zengyiheng/project/zyh-pipeline/snpeff/snpEff/snpEff.config
cadd_dir=/genetics/home/zengyiheng/project/zyh-pipeline/gript/GRIPT_BCM/CADD_score
gnomad_dir=/genetics/home/zengyiheng/project/zyh-pipeline/gript/GRIPT_BCM/Data/gnomad
perl ${gript_dir}/1preprocess_vcf.pl \
-i ${work_dir}/case/vcf \
-o ${work_dir}/case/score \
-sfj ${snpeff_jar} \
-sfc ${snpeff_config} \
-rt GATK \
-cd_snp ${cadd_dir}/whole_genome_SNVs.tsv.gz \
-cd_ind ${cadd_dir}/InDels.tsv.gz \
-gn ${gnomad_dir}/gnomad_exomes_r2.0.1.sites_sort_5-26-2017.gz

### error reported###
Argument "." isn't numeric in numeric gt (>) at /genetics/home/zengyiheng/project/zyh-pipeline/gript/GRIPT_BCM/1preprocess_vcf.pl line 233, <INPUTtbx> line 66.
Argument "." isn't numeric in numeric gt (>) at /genetics/home/zengyiheng/project/zyh-pipeline/gript/GRIPT_BCM/1preprocess_vcf.pl line 233, <INPUTtbx> line 7083.
Argument "." isn't numeric in numeric gt (>) at /genetics/home/zengyiheng/project/zyh-pipeline/gript/GRIPT_BCM/1preprocess_vcf.pl line 233, <INPUTtbx> line 9192.
Argument "." isn't numeric in numeric gt (>) at /genetics/home/zengyiheng/project/zyh-pipeline/gript/GRIPT_BCM/1preprocess_vcf.pl line 233, <INPUTtbx> line 12532.
Argument "." isn't numeric in numeric gt (>) at /genetics/home/zengyiheng/project/zyh-pipeline/gript/GRIPT_BCM/1preprocess_vcf.pl line 233, <INPUTtbx> line 12610.
Argument "." isn't numeric in numeric gt (>) at /genetics/home/zengyiheng/project/zyh-pipeline/gript/GRIPT_BCM/1preprocess_vcf.pl line 233, <INPUTtbx> line 25266.

Could you please be so kind to help with this? I don't know why this happened. Thank you again.

Sincerely,
Yi-Heng Zeng

**Comment by fe4960** [comment]
Hi Yi-Heng,

Sorry for the late reply. This is due to the allele frequency is "." but not a digital/number. You can ignore this error info and continue the analysis. I also update the script to address the issue. So you can also download the updated script and rerun this step.

Best regards,
Jun

**Comment by fjmuzengyiheng** [comment]
> Hi Yi-Heng,
> 
> Sorry for the late reply. This is due to the allele frequency is "." but not a digital/number. You can ignore this error info and continue the analysis. I also update the script to address the issue. So you can also download the updated script and rerun this step.
> 
> Best regards, Jun


Thank you a lot. It is nice of you. The new script worked well.    : - )
