### ISSUE TITLE
About CADD score for Indels.

### ISSUE THREAD

**Issue by fjmuzengyiheng** [fe4960/GRIPT_BCM#5]
Hi, thank you for this tool. I have been tested the tool and found it of great help.

However, it seemed Indels absent from InDels.tsv.gz file (obtained from https://cadd.gs.washington.edu/download) were documented in GRIPT_CADD_missing. I failed to prioritize **novel Indels** in my recent tests.

Could you please be so kind to help with this? Thank you again. 

Sincerely, 
Yi-Heng Zeng

**Comment by fe4960** [comment]
You can get the CADD score of the novel Indels from the https://cadd.gs.washington.edu/score, and select the correct version corresponding to the InDels.tsv.gz file you have. Then add these annotated CADD score to your input and run GRIPT.
