### ISSUE TITLE
Update REVEL score for GRIPT

### ISSUE THREAD

**Issue by HelenCeleste** [fe4960/GRIPT_BCM#6]
Hi,
Thank you for providing this tools

I've read the paper and notice that you've test the Revel score in the paper. 
Recently, a lot of research has shown that REVEL perform better than CADD. So is it possible to make GRIPT be compatible with REVEL?  

Thanks a lot!

**Comment by fe4960** [comment]
GRIPT can also work with REVEL. You just need to provide REVEL score in the input file.
